"""add participants_json to arena_matches

Revision ID: 079220a0d96f
Revises: 16ffe9f00e9e
Create Date: 2026-04-24 00:24:33.945222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079220a0d96f'
down_revision: Union[str, Sequence[str], None] = '16ffe9f00e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arena_matches', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('participants_json', sa.String(length=4096), nullable=False, server_default='[]')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arena_matches', schema=None) as batch_op:
        batch_op.drop_column('participants_json')

    # ### end Alembic commands ###
