"""add admin columns

Revision ID: 0b5a510f47b6
Revises: 6f5ba688327f
Create Date: 2026-04-23 08:22:56.425921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5a510f47b6'
down_revision: Union[str, Sequence[str], None] = '6f5ba688327f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so existing rows backfill; kept on the column afterwards
    # (it's a no-op for ORM-driven inserts, which always supply the value).
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('banned_reason', sa.String(length=256), nullable=False, server_default='')
        )
        batch_op.create_index(batch_op.f('ix_accounts_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_banned'), ['is_banned'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_is_banned'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_admin'))
        batch_op.drop_column('banned_reason')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
