"""add friendships + direct messages + reports

Revision ID: 149db89557a5
Revises: 165138cd2979
Create Date: 2026-04-25 03:02:45.614361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149db89557a5'
down_revision: Union[str, Sequence[str], None] = '165138cd2979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('other_account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['other_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'other_account_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_other_account_id'), ['other_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_status'), ['status'], unique=False)

    op.create_table('direct_message_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['direct_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direct_message_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_message_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_message_reports_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_message_reports_reporter_id'), ['reporter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_message_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_direct_message_reports_message_id'))
        batch_op.drop_index(batch_op.f('ix_direct_message_reports_created_at'))

    op.drop_table('direct_message_reports')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_status'))
        batch_op.drop_index(batch_op.f('ix_friendships_other_account_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_created_at'))
        batch_op.drop_index(batch_op.f('ix_friendships_account_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_read_at'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_created_at'))

    op.drop_table('direct_messages')
    # ### end Alembic commands ###
