"""add account level + xp + story state

Revision ID: 165138cd2979
Revises: 43fbbed7e68d
Create Date: 2026-04-25 02:53:58.074853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165138cd2979'
down_revision: Union[str, Sequence[str], None] = '43fbbed7e68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('account_level', sa.Integer(), nullable=False, server_default='1'),
        )
        batch_op.add_column(
            sa.Column('account_xp', sa.Integer(), nullable=False, server_default='0'),
        )
        batch_op.add_column(
            sa.Column('story_state_json', sa.String(length=2048),
                      nullable=False, server_default='{}'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('story_state_json')
        batch_op.drop_column('account_xp')
        batch_op.drop_column('account_level')

    # ### end Alembic commands ###
