"""add admin_announcements

Revision ID: 16ffe9f00e9e
Revises: 7d4dde3d3009
Create Date: 2026-04-24 00:12:03.737919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ffe9f00e9e'
down_revision: Union[str, Sequence[str], None] = '7d4dde3d3009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=2048), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_announcements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_announcements_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_announcements_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_announcements_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_announcements_starts_at'), ['starts_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_announcements_starts_at'))
        batch_op.drop_index(batch_op.f('ix_admin_announcements_priority'))
        batch_op.drop_index(batch_op.f('ix_admin_announcements_is_active'))
        batch_op.drop_index(batch_op.f('ix_admin_announcements_ends_at'))
        batch_op.drop_index(batch_op.f('ix_admin_announcements_created_at'))

    op.drop_table('admin_announcements')
    # ### end Alembic commands ###
