"""add daily_quests

Revision ID: 18991b195b7b
Revises: 4a82677042d0
Create Date: 2026-04-22 21:29:59.991812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18991b195b7b'
down_revision: Union[str, Sequence[str], None] = '4a82677042d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('day_key', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_key', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('reward_gems', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('reward_shards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_quests_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_day_key'), ['day_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_quests_status'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_day_key'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_account_id'))

    op.drop_table('daily_quests')
    # ### end Alembic commands ###
