"""add stripe_price_id to shop products

Revision ID: 1e7b82d9ecf6
Revises: 7334999644aa
Create Date: 2026-04-23 16:18:39.670136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7b82d9ecf6'
down_revision: Union[str, Sequence[str], None] = '7334999644aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stripe_price_id', sa.String(length=64), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
