"""add participants_json to battles

Revision ID: 2c5a7db83f97
Revises: 76b920b4aa57
Create Date: 2026-04-23 12:22:57.912474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5a7db83f97'
down_revision: Union[str, Sequence[str], None] = '76b920b4aa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('participants_json', sa.String(length=4096), nullable=False, server_default='[]')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_column('participants_json')

    # ### end Alembic commands ###
