"""add energy refill tracking

Revision ID: 36328ec6a6b5
Revises: 7c0d436421a0
Create Date: 2026-04-24 00:55:51.191746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36328ec6a6b5'
down_revision: Union[str, Sequence[str], None] = '7c0d436421a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('refills_today_key', sa.String(length=10), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('refills_today_count', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('refills_today_count')
        batch_op.drop_column('refills_today_key')

    # ### end Alembic commands ###
