"""add session metadata to refresh_tokens

Revision ID: 3aa50c822bb6
Revises: 149db89557a5
Create Date: 2026-04-25 06:26:34.432190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa50c822bb6'
down_revision: Union[str, Sequence[str], None] = '149db89557a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('created_ip')

    # ### end Alembic commands ###
