"""add totp 2fa fields

Revision ID: 417b4bf770de
Revises: 2846156b1778
Create Date: 2026-04-24 02:36:51.551698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417b4bf770de'
down_revision: Union[str, Sequence[str], None] = '2846156b1778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('totp_secret', sa.String(length=64), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_accounts_totp_enabled'), ['totp_enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_totp_enabled'))
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
