"""add difficulty_tier + requires_code to stages

Revision ID: 4395c6693615
Revises: 1e7b82d9ecf6
Create Date: 2026-04-23 18:50:15.938852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4395c6693615'
down_revision: Union[str, Sequence[str], None] = '1e7b82d9ecf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('difficulty_tier', sa.String(length=16), nullable=False, server_default='NORMAL')
        )
        batch_op.add_column(
            sa.Column('requires_code', sa.String(length=64), nullable=False, server_default='')
        )
        batch_op.create_index(batch_op.f('ix_stages_difficulty_tier'), ['difficulty_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_difficulty_tier'))
        batch_op.drop_column('requires_code')
        batch_op.drop_column('difficulty_tier')

    # ### end Alembic commands ###
