"""initial schema

Revision ID: 4a82677042d0
Revises: 
Create Date: 2026-04-22 21:16:42.635990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a82677042d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('shards', sa.Integer(), nullable=False),
    sa.Column('energy_stored', sa.Integer(), nullable=False),
    sa.Column('energy_last_tick_at', sa.DateTime(), nullable=False),
    sa.Column('pulls_since_epic', sa.Integer(), nullable=False),
    sa.Column('stages_cleared_json', sa.String(length=1024), nullable=False),
    sa.Column('arena_rating', sa.Integer(), nullable=False),
    sa.Column('arena_wins', sa.Integer(), nullable=False),
    sa.Column('arena_losses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_arena_rating'), ['arena_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)

    op.create_table('hero_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('faction', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_atk', sa.Integer(), nullable=False),
    sa.Column('base_def', sa.Integer(), nullable=False),
    sa.Column('base_spd', sa.Integer(), nullable=False),
    sa.Column('basic_mult', sa.Float(), nullable=False),
    sa.Column('special_json', sa.String(length=1024), nullable=False),
    sa.Column('special_cooldown', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_templates_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_hero_templates_rarity'), ['rarity'], unique=False)

    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=False),
    sa.Column('recommended_power', sa.Integer(), nullable=False),
    sa.Column('waves_json', sa.String(length=4096), nullable=False),
    sa.Column('coin_reward', sa.Integer(), nullable=False),
    sa.Column('first_clear_gems', sa.Integer(), nullable=False),
    sa.Column('first_clear_shards', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stages_order'), ['order'], unique=False)

    op.create_table('arena_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('defender_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('rating_delta', sa.Integer(), nullable=False),
    sa.Column('attacker_rating_after', sa.Integer(), nullable=False),
    sa.Column('defender_rating_after', sa.Integer(), nullable=False),
    sa.Column('log_json', sa.String(length=65536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arena_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arena_matches_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arena_matches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_arena_matches_defender_id'), ['defender_id'], unique=False)

    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('team_json', sa.String(length=1024), nullable=False),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('log_json', sa.String(length=65536), nullable=False),
    sa.Column('rewards_json', sa.String(length=1024), nullable=False),
    sa.Column('first_clear', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battles_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_battles_stage_id'), ['stage_id'], unique=False)

    op.create_table('defense_teams',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('hero_ids_json', sa.String(length=256), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    with op.batch_alter_table('defense_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defense_teams_power'), ['power'], unique=False)

    op.create_table('gacha_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('pity_before', sa.Integer(), nullable=False),
    sa.Column('pulled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['hero_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gacha_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_records_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_records_pulled_at'), ['pulled_at'], unique=False)

    op.create_table('hero_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('special_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['hero_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_instances_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hero_instances_template_id'), ['template_id'], unique=False)

    op.create_table('gear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('stats_json', sa.String(length=512), nullable=False),
    sa.Column('hero_instance_id', sa.Integer(), nullable=True),
    sa.Column('obtained_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hero_instance_id'], ['hero_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gear_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gear_hero_instance_id'), ['hero_instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_hero_instance_id'))
        batch_op.drop_index(batch_op.f('ix_gear_account_id'))

    op.drop_table('gear')
    with op.batch_alter_table('hero_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_instances_template_id'))
        batch_op.drop_index(batch_op.f('ix_hero_instances_account_id'))

    op.drop_table('hero_instances')
    with op.batch_alter_table('gacha_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_records_pulled_at'))
        batch_op.drop_index(batch_op.f('ix_gacha_records_account_id'))

    op.drop_table('gacha_records')
    with op.batch_alter_table('defense_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defense_teams_power'))

    op.drop_table('defense_teams')
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battles_stage_id'))
        batch_op.drop_index(batch_op.f('ix_battles_created_at'))
        batch_op.drop_index(batch_op.f('ix_battles_account_id'))

    op.drop_table('battles')
    with op.batch_alter_table('arena_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arena_matches_defender_id'))
        batch_op.drop_index(batch_op.f('ix_arena_matches_created_at'))
        batch_op.drop_index(batch_op.f('ix_arena_matches_attacker_id'))

    op.drop_table('arena_matches')
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_order'))
        batch_op.drop_index(batch_op.f('ix_stages_code'))

    op.drop_table('stages')
    with op.batch_alter_table('hero_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_templates_rarity'))
        batch_op.drop_index(batch_op.f('ix_hero_templates_code'))

    op.drop_table('hero_templates')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_email'))
        batch_op.drop_index(batch_op.f('ix_accounts_arena_rating'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
