"""add guilds and active sets

Revision ID: 5baf9e910164
Revises: 84f12ce0a0a1
Create Date: 2026-04-23 05:58:21.164574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5baf9e910164'
down_revision: Union[str, Sequence[str], None] = '84f12ce0a0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=6), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('guild_members',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    with op.batch_alter_table('guild_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_members_guild_id'), ['guild_id'], unique=False)

    op.create_table('guild_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guild_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_messages_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_messages_guild_id'))
        batch_op.drop_index(batch_op.f('ix_guild_messages_created_at'))

    op.drop_table('guild_messages')
    with op.batch_alter_table('guild_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_members_guild_id'))

    op.drop_table('guild_members')
    op.drop_table('guilds')
    # ### end Alembic commands ###
