"""add account.event_state_json

Revision ID: 69456f77c30c
Revises: eeb5a4eba1da
Create Date: 2026-04-24 19:49:27.874480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69456f77c30c'
down_revision: Union[str, Sequence[str], None] = 'eeb5a4eba1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('event_state_json', sa.String(length=8192),
                      nullable=False, server_default='{}'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('event_state_json')

    # ### end Alembic commands ###
