"""liveops and raids

Revision ID: 6f5ba688327f
Revises: 5baf9e910164
Create Date: 2026-04-23 06:21:14.481689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5ba688327f'
down_revision: Union[str, Sequence[str], None] = '5baf9e910164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liveops_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liveops_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liveops_events_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_liveops_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_liveops_events_starts_at'), ['starts_at'], unique=False)

    op.create_table('raids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('boss_template_id', sa.Integer(), nullable=False),
    sa.Column('boss_level', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('remaining_hp', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boss_template_id'], ['hero_templates.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raids_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raids_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raids_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raids_state'), ['state'], unique=False)

    op.create_table('raid_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raid_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raid_attempts_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raid_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raid_attempts_raid_id'), ['raid_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raid_attempts_raid_id'))
        batch_op.drop_index(batch_op.f('ix_raid_attempts_created_at'))
        batch_op.drop_index(batch_op.f('ix_raid_attempts_account_id'))

    op.drop_table('raid_attempts')
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raids_state'))
        batch_op.drop_index(batch_op.f('ix_raids_started_at'))
        batch_op.drop_index(batch_op.f('ix_raids_guild_id'))
        batch_op.drop_index(batch_op.f('ix_raids_ends_at'))

    op.drop_table('raids')
    with op.batch_alter_table('liveops_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liveops_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_liveops_events_kind'))
        batch_op.drop_index(batch_op.f('ix_liveops_events_ends_at'))

    op.drop_table('liveops_events')
    # ### end Alembic commands ###
