"""add shop products + purchases + ledger

Revision ID: 7334999644aa
Revises: c60e24b5c96b
Create Date: 2026-04-23 15:41:59.499910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7334999644aa'
down_revision: Union[str, Sequence[str], None] = 'c60e24b5c96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('contents_json', sa.String(length=1024), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('per_account_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_products_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_shop_products_sort_order'), ['sort_order'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title_snapshot', sa.String(length=128), nullable=False),
    sa.Column('price_cents_paid', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('processor', sa.String(length=32), nullable=False),
    sa.Column('processor_ref', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('contents_snapshot_json', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_reason', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processor', 'processor_ref')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_processor'), ['processor'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_processor_ref'), ['processor_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_state'), ['state'], unique=False)

    op.create_table('purchase_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_ledger_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_ledger_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_ledger_purchase_id'), ['purchase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_ledger_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_ledger_kind'))
        batch_op.drop_index(batch_op.f('ix_purchase_ledger_direction'))
        batch_op.drop_index(batch_op.f('ix_purchase_ledger_created_at'))

    op.drop_table('purchase_ledger')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_state'))
        batch_op.drop_index(batch_op.f('ix_purchases_sku'))
        batch_op.drop_index(batch_op.f('ix_purchases_processor_ref'))
        batch_op.drop_index(batch_op.f('ix_purchases_processor'))
        batch_op.drop_index(batch_op.f('ix_purchases_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchases_account_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_products_sort_order'))
        batch_op.drop_index(batch_op.f('ix_shop_products_sku'))
        batch_op.drop_index(batch_op.f('ix_shop_products_kind'))
        batch_op.drop_index(batch_op.f('ix_shop_products_is_active'))

    op.drop_table('shop_products')
    # ### end Alembic commands ###
