"""add daily login streak fields

Revision ID: 7c0d436421a0
Revises: 079220a0d96f
Create Date: 2026-04-24 00:33:41.574601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0d436421a0'
down_revision: Union[str, Sequence[str], None] = '079220a0d96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_daily_claim_at', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('daily_streak', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('daily_streak')
        batch_op.drop_column('last_daily_claim_at')

    # ### end Alembic commands ###
