"""add tier to raids

Revision ID: 7d4dde3d3009
Revises: 4395c6693615
Create Date: 2026-04-23 19:03:05.483493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4dde3d3009'
down_revision: Union[str, Sequence[str], None] = '4395c6693615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('tier', sa.String(length=8), nullable=False, server_default='T1')
        )
        batch_op.create_index(batch_op.f('ix_raids_tier'), ['tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raids_tier'))
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
