"""add stars set_code

Revision ID: 84f12ce0a0a1
Revises: 18991b195b7b
Create Date: 2026-04-22 21:58:35.893514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f12ce0a0a1'
down_revision: Union[str, Sequence[str], None] = '18991b195b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default fills existing rows; we keep the NOT NULL guarantee for new ones.
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('set_code', sa.String(length=16), nullable=False, server_default='VITAL')
        )
    with op.batch_alter_table('hero_instances', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stars', sa.Integer(), nullable=False, server_default='1')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_instances', schema=None) as batch_op:
        batch_op.drop_column('stars')

    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.drop_column('set_code')

    # ### end Alembic commands ###
