"""add email verification

Revision ID: 939f3a7de9f1
Revises: ae135fabeea0
Create Date: 2026-04-24 01:15:29.703835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939f3a7de9f1'
down_revision: Union[str, Sequence[str], None] = 'ae135fabeea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accounts_email_verified'), ['email_verified'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_email_verified'))
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_created_at'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_account_id'))

    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
