"""add craft_materials and craft_log

Revision ID: 95428f4b6cc6
Revises: f1c5ab519e92
Create Date: 2026-04-24 20:16:54.866533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95428f4b6cc6'
down_revision: Union[str, Sequence[str], None] = 'f1c5ab519e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('recipe_code', sa.String(length=64), nullable=False),
    sa.Column('inputs_json', sa.String(length=512), nullable=False),
    sa.Column('output_summary', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('craft_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_craft_log_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_craft_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_craft_log_recipe_code'), ['recipe_code'], unique=False)

    op.create_table('craft_materials',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('craft_materials')
    with op.batch_alter_table('craft_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_craft_log_recipe_code'))
        batch_op.drop_index(batch_op.f('ix_craft_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_craft_log_account_id'))

    op.drop_table('craft_log')
    # ### end Alembic commands ###
