"""phase 1.1 - free_summon_credits + tutorial_reward_granted

Revision ID: 99c5b4700c77
Revises: 9cf7a9bcc266
Create Date: 2026-04-24 15:39:51.134553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c5b4700c77'
down_revision: Union[str, Sequence[str], None] = '9cf7a9bcc266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('free_summon_credits', sa.Integer(),
                      nullable=False, server_default='0'),
        )
        batch_op.add_column(
            sa.Column('tutorial_reward_granted', sa.Boolean(),
                      nullable=False, server_default=sa.false()),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('tutorial_reward_granted')
        batch_op.drop_column('free_summon_credits')

    # ### end Alembic commands ###
