"""add totp recovery codes

Revision ID: 9cf7a9bcc266
Revises: 417b4bf770de
Create Date: 2026-04-24 02:45:35.788630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf7a9bcc266'
down_revision: Union[str, Sequence[str], None] = '417b4bf770de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totp_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('totp_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_totp_recovery_codes_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_totp_recovery_codes_code_hash'), ['code_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('totp_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_totp_recovery_codes_code_hash'))
        batch_op.drop_index(batch_op.f('ix_totp_recovery_codes_account_id'))

    op.drop_table('totp_recovery_codes')
    # ### end Alembic commands ###
