"""add guild_applications

Revision ID: a3791cf5ba46
Revises: 2c5a7db83f97
Create Date: 2026-04-23 12:33:22.122451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3791cf5ba46'
down_revision: Union[str, Sequence[str], None] = '2c5a7db83f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guild_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_applications_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_applications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_applications_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_applications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_applications_status'))
        batch_op.drop_index(batch_op.f('ix_guild_applications_guild_id'))
        batch_op.drop_index(batch_op.f('ix_guild_applications_created_at'))
        batch_op.drop_index(batch_op.f('ix_guild_applications_account_id'))

    op.drop_table('guild_applications')
    # ### end Alembic commands ###
