"""add inventory slot caps and mailbox

Revision ID: cea1bbf6c57a
Revises: 95428f4b6cc6
Create Date: 2026-04-24 20:23:56.673595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea1bbf6c57a'
down_revision: Union[str, Sequence[str], None] = '95428f4b6cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('hero_slot_cap', sa.Integer(),
                      nullable=False, server_default='50'),
        )
        batch_op.add_column(
            sa.Column('gear_slot_cap', sa.Integer(),
                      nullable=False, server_default='200'),
        )
        batch_op.add_column(
            sa.Column('mailbox_overflow_json', sa.String(length=8192),
                      nullable=False, server_default='[]'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('mailbox_overflow_json')
        batch_op.drop_column('gear_slot_cap')
        batch_op.drop_column('hero_slot_cap')

    # ### end Alembic commands ###
