"""add hero_templates mana columns

Revision ID: d515d104feb9
Revises: f019b3d4ab7e
Create Date: 2026-04-27 00:07:36.826998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd515d104feb9'
down_revision: Union[str, Sequence[str], None] = 'f019b3d4ab7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mana_cost', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('mana_regen_per_turn', sa.Integer(), nullable=False, server_default='15'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_templates', schema=None) as batch_op:
        batch_op.drop_column('mana_regen_per_turn')
        batch_op.drop_column('mana_cost')

    # ### end Alembic commands ###
