"""add account.achievements_json

Revision ID: daa44faf8617
Revises: cea1bbf6c57a
Create Date: 2026-04-25 01:54:46.353325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa44faf8617'
down_revision: Union[str, Sequence[str], None] = 'cea1bbf6c57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('achievements_json', sa.String(length=4096),
                      nullable=False, server_default='{}'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('achievements_json')

    # ### end Alembic commands ###
