"""phase 1.3 - team_presets

Revision ID: eeb5a4eba1da
Revises: 99c5b4700c77
Create Date: 2026-04-24 15:50:51.037681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb5a4eba1da'
down_revision: Union[str, Sequence[str], None] = '99c5b4700c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('hero_ids_json', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_preset_per_account')
    )
    with op.batch_alter_table('team_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_presets_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_presets_account_id'))

    op.drop_table('team_presets')
    # ### end Alembic commands ###
