"""add shard_exchanges counter to accounts

Revision ID: f1c5ab519e92
Revises: 69456f77c30c
Create Date: 2026-04-24 20:11:33.710290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c5ab519e92'
down_revision: Union[str, Sequence[str], None] = '69456f77c30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('shard_exchanges_today_key', sa.String(length=10),
                      nullable=False, server_default=''),
        )
        batch_op.add_column(
            sa.Column('shard_exchanges_today_count', sa.Integer(),
                      nullable=False, server_default='0'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('shard_exchanges_today_count')
        batch_op.drop_column('shard_exchanges_today_key')

    # ### end Alembic commands ###
