"""Generate frontend/src/battle3d/archetypeMap.ts from app/rig_map.py.

Maps each template_code to a 3D archetype. Source of truth is
RIG_FOR_TEMPLATE; this script collapses the rig name onto the smaller
set of 7 archetypes (6 KayKit + Druid) via RIG_TO_ARCHETYPE.

Run from repo root:

    uv run python scripts/gen-archetype-map.py
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure repo root is importable regardless of cwd.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from app.rig_map import RIG_FOR_TEMPLATE  # noqa: E402

# Manual collapse of rig names -> 3D archetype. Anything not listed falls
# back to DEFAULT_ARCHETYPE = "knight".
RIG_TO_ARCHETYPE: dict[str, str] = {
    # Direct archetypes (placeholder rig names that may exist)
    "stick-figure":  "knight",
    "knight":        "knight",
    "barbarian":     "barbarian",
    "mage":          "mage",
    "rogue":         "rogue",
    "rogue-hooded":  "rogue_hooded",
    "ranger":        "ranger",
    "druid":         "druid",
    "engineer":      "ranger",  # remapped — no engineer model in v1

    # CraftPix rigs currently in RIG_FOR_TEMPLATE — collapse onto the
    # closest visual archetype.
    "knight-1":          "knight",
    "knight-2":          "knight",
    "knight-3":          "knight",
    "kunoichi":          "rogue_hooded",
    "ninja-monk":        "rogue",
    "ninja-peasant":     "rogue",
    "wanderer-magican":  "mage",
    "fire-wizard":       "mage",
    "lightning-mage":    "mage",
    "kitsune":           "rogue_hooded",
    "karasu-tengu":      "ranger",
    "yamabushi-tengu":   "druid",
    "satyr-1":           "barbarian",
    "satyr-2":           "barbarian",
    "satyr-3":           "barbarian",
    "minotaur-1":        "barbarian",
    "minotaur-2":        "barbarian",
    "minotaur-3":        "barbarian",
    "gorgon-1":          "mage",
    "gorgon-2":          "mage",
    "red-werewolf":      "barbarian",
    "black-werewolf":    "rogue",
    "dark-assassin":     "rogue_hooded",
}

DEFAULT_ARCHETYPE = "knight"


def main() -> None:
    lines = [
        "// AUTO-GENERATED by scripts/gen-archetype-map.py — do not edit by hand.",
        "// Run `uv run python scripts/gen-archetype-map.py` to regenerate.",
        "",
        "export const TEMPLATE_TO_3D_ARCHETYPE: Record<string, string> = {",
    ]
    for template_code, rig in sorted(RIG_FOR_TEMPLATE.items()):
        archetype = RIG_TO_ARCHETYPE.get(rig, DEFAULT_ARCHETYPE)
        lines.append(f'  "{template_code}": "{archetype}",')
    lines.append("};")
    lines.append("")
    lines.append(f'export const DEFAULT_3D_ARCHETYPE = "{DEFAULT_ARCHETYPE}";')
    lines.append("")
    out = Path("frontend/src/battle3d/archetypeMap.ts")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(RIG_FOR_TEMPLATE)} entries)")


if __name__ == "__main__":
    main()
